WIP: Add ability for cache to do Cleanup
drone/drone-cache-lib pull request #1
Opened 2016-12-21 21:17 UTC by jmccann

This is my stab at providing base functionality for cache plugins to be able to cleanup old archives.

2016-12-21 21:58 UTC, donny-dont requested changes
Please verify we can do everything we want to with just FileInfo. If not we can go from there.

2016-12-21 21:58 UTC, donny-dont commented on storage/storage.go
> +type File struct {
It looks like FileInfo contains the actual Name. See https://golang.org/src/os/types.go?s=391:752#L6 so I don't think you need to make a new struct here. So for like s3 in the list you would create the FileInfo and add the name and add the modified time and then things would just work.

2016-12-21 22:01 UTC, jmccann commented on storage/storage.go
> +type File struct {
`FileInfo` does not contain the path, only the base name of the file with `Name()`.  That is why I created the `File` struct ... to keep the `Path` along with the `FileInfo` details.

2016-12-21 22:05 UTC, donny-dont commented on storage/storage.go
> +type File struct {
Ah okay I misunderstood the struct. I don't like the name though. Maybe `FileEntry`?.

Also let me ask @bradrydzewski if there's something already around which is similar to what we want already in the library. Or maybe he would prefer something like a Walk function.

2016-12-21 22:11 UTC, jmccann commented on storage/storage.go
> +type File struct {
I'll update from `File` to `FileEntry` and we can see what @bradrydzewski 's input is to this all in general.  :)

2016-12-22 15:18 UTC, bradrydzewski commented
one idea might be to create a `cache.Flusher` interface, with a `cache.TimeFlusher` as the default implementation. With an optional `NoopFlusher` for individuals that don't want this functionality. These could get passed to cache in the constructor

```diff
type Cache struct {
	s storage.Storage
+	a archive.Archiver
+	f Flusher
}

-func New(s storage.Storage) (Cache, error) {
+func New(s storage.Storage, a archive.Archiver, f Flusher) Cache {
	return Cache{ s: s, a: a, f: f }
}
```

Note that I think we should also pass the archiver into the new function. That way the individual using the library has direct control over the compression algorithm being used, and can customize without asking for changes in the lib.

Since most people probably won't need to customize, we can probably provide the following function to set the following defaults:

```
func NewDefault(s storage.Storage) Cache {
	return New(s, new(archiver.TarArchiver), new(TimeFlusher))
}
```

2016-12-22 20:21 UTC, jmccann commented
@bradrydzewski @donny-dont I tried to create a `Flusher`.  Not sure I did it entirely right.  I feel overall this is better but still not where we want it.  Unfortunately I'm still new to designing stuff so it's not coming naturally to me.  Give me enough direction and I can fix/clean this up more.  Thanks for the reviews!

2017-01-03 21:42 UTC, bradrydzewski commented
> Not sure I did it entirely right

agreed, I'm starting to think flusher should not be used by the cache struct? Maybe it should be a separate thing, instead?

```Go
f := cache.NewFlusher(s)
f.IsDirty = func(f *File) bool {
  return file.Timestamp().After(time.Now() - time.Days - 30) // this won't work, I realize. Just pseudo-code
}
f.Flush()
```

2017-01-05 02:12 UTC, jmccann commented
I removed `Flusher` from `Cache`.  It should be called directly by a plugin that wants to cleanup files.

I think I got close (or maybe accomplished) what you were describing @bradrydzewski ?

I'm feeling a lot better about how this looks personally.  Let me know of any other thoughts/comments.  If you guys think it's looking good then I'll try implementing for reals in the `drone-s3-cache` to see if it'll really really work.  😄

2017-01-05 02:58 UTC, bradrydzewski commented on flusher/flusher.go
> +		// Do not delete directories
In this case you don't need to return a function, you can just do this:

```
func TimeOp(file storage.FileEntry) bool {
 ...
}
```

2017-01-05 03:03 UTC, bradrydzewski commented
Looking great. I added one inline comment. The only other minor comment I have is that I would probably put flusher inside of the cache package. There is of course no hard rule when to put something in a separate package or not. I can't articulate why, but it feels like it belongs in cache :)

2017-01-05 14:18 UTC, jmccann commented on flusher/flusher.go
> +		// Do not delete directories
How do I then assign the function in `NewDefaultFlusher` @ https://github.com/drone/drone-cache-lib/blob/7966928e65d26567af5eded3326bd01316b031dc/cache/flusher.go#L23 ?

2017-01-05 14:20 UTC, jmccann commented
I made the updates.

I added a question/comment to your inline comment.  I'll get that cleared up once I have an answer.  :)

Also, just curious how to handle testing between `cache_test.go` and `flusher_test.go`.  They use of some of the fixture functions.  Is it OK how it is and have them declared in `cache_test.go` and use in `flusher_test.go`?  Or should I put shared functions in a separate file?

2017-01-05 15:09 UTC, bradrydzewski commented
> How do I then assign the function in NewDefaultFlusher

You can assign the function like this:

```
func NewDefaultFlusher(s storage.Storage) Flusher {
	return Flusher{ store: s, dirty: IsExpired }
}
```

Where the function is defined like this:

```
func IsExpired(file storage.FileEntry) bool {
    ....
    return true
}
```

Note that I would recommend the minor name change, just to be a bit more descriptive :)

> Also, just curious how to handle testing between cache_test.go and flusher_test.go. They use some of the same fixture functions. 

I think what you have now is pretty good.

I do think it could be improved by removing the fixtures all together and using a [filesystem interface](https://golang.org/pkg/net/http/#FileSystem) and a [mock](https://github.com/golang/mock) testing library.  This would probably remove the fixtures all together. But I would say this could be explored at another time :)

2017-01-05 20:20 UTC, merged

2017-01-05 20:21 UTC, bradrydzewski commented
awesome, thanks @jmccann !